### ISSUE TITLE
fails on old node

### ISSUE THREAD

**Issue by WardCunningham** [WardCunningham/wiki-plugin-datalog#1]
```
starting plugin wiki-plugin-datalog
failed to start plugin wiki-plugin-datalog SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/usr/local/lib/node_modules/wiki/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/wiki/node_modules/wiki-server/lib/plugins.coffee:31:24
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

developed on v6.11.1
deployed to v4.4.7

**Comment by WardCunningham** [comment]
aa30674740b2dfc74c8b4471a86bc9a3d5478c96 72e8454539c5596ec7cefd4df5478954ca51618a 6ad4c017d87c633cac86075d0d0ee2bf8fb483f5 sufficently address this problem.
